# $HOME/.config/alacritty/alacritty.toml
# by Jen Liang 2026-02-21

[window] 

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

# Font can be found here: https://www.programmingfonts.org/#fantasque-sans
normal.family = "FantasqueSansM Nerd Font Propo"
bold.family = "FantasqueSansM Nerd Font Propo"
italic.family = "FantasqueSansM Nerd Font Propo"
bold_italic.family = "FantasqueSansM Nerd Font Propo"

size = 13.0
