# $HOME/.config/alacritty/alacritty.toml
# by Jen Liang 2026-02-21

[window] 

opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

dynamic_title = true

[font]

# Font can be found here: https://www.programmingfonts.org/#fantasque-sans
normal.family = "FantasqueSansM Nerd Font Mono"
bold.family = "FantasqueSansM Nerd Font Mono"
italic.family = "FantasqueSansM Nerd Font Mono"
bold_italic.family = "FantasqueSansM Nerd Font Mono"

size = 13.0

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]
